import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`font-brand-regular antialiased`}
      >
        <Header />
        <div className="max-w-[1920px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
